// ── Real bird pool ────────────────────────────────────────────────────────────
// Flat list — startRound() picks 2 at random each game.
const BIRDS = [
  { name: "Magnificent Frigatebird",
    fact: "Males inflate a bright red throat pouch the size of a football to attract mates. They can stay airborne for up to two months straight, sleeping while they glide." },
  { name: "Hoatzin",
    fact: "Chicks are born with claws on their wings to climb trees — a trait not seen in other modern birds. Adults smell so strongly of manure they're called 'stinkbirds.'" },
  { name: "Shoebill",
    fact: "Its bill looks like a Dutch clog and can snap shut with enough force to decapitate a lungfish. It freezes statue-still for hours, then strikes with shocking speed." },
  { name: "Potoo",
    fact: "Potoos disguise themselves as broken tree stumps so convincingly that people walk right past them. They have notches in their closed eyelids so they can 'see' while pretending to be asleep." },
  { name: "Superb Bird-of-Paradise",
    fact: "The male transforms his body into an oval of iridescent blue-green to perform a dance for females. Scientists say it's one of the most surreal courtship displays ever recorded." },
  { name: "Kakapo",
    fact: "The world's fattest parrot is also entirely flightless and smells like flowers. It mates once every few years when a certain fruit tree blooms, so the whole species goes into a frenzy at the same time." },
  { name: "Satanic Nightjar",
    fact: "Named after a local legend in Sulawesi that said it was a messenger of evil. In reality it's a harmless, bug-eating bird — but it does have fiery orange eyes that glow in the dark." },
  { name: "Long-wattled Umbrellabird",
    fact: "The male sports a crest like a huge black umbrella and a dangling wattle up to 35cm long. He inflates it to boom like a foghorn to attract females." },
  { name: "Wilson's Bird-of-Paradise",
    fact: "Found on a single tiny island in Indonesia. The male has bare turquoise skin on its head, a curled blue tail wire, and a cape of yellow and red. The bare scalp acts like a stage light, brightening during courtship." },
  { name: "Spectacled Eider",
    fact: "Winters in enormous Arctic flocks of nearly 400,000 birds on the Bering Sea. They dive through holes in the ice to feed on clams. The male's goggle-like eye patches give it the look of a very stylish diver." },
  { name: "Ribbon-tailed Astrapia",
    fact: "The male has tail feathers over 1 metre long — three times its body length. It's found only in a small part of New Guinea's highlands and the tails are prized as ornaments by local tribes." },
  { name: "Helmeted Hornbill",
    fact: "Unlike other hornbills, its casque is solid ivory. That made it a target for carvers — it's now more trafficked than elephant ivory in parts of Asia. Its call sounds like a human laughing, then speeding up to a hysterical cackle." },
  { name: "Cock-of-the-rock",
    fact: "The male is neon orange and looks like someone glued a UFO to its head. Males gather in groups called leks and show off together — the female wanders through and picks whoever she likes." },
  { name: "Macaroni Penguin",
    fact: "Named by British explorers after the 18th-century fashion of wearing extravagant feathered hats. With 18 million individuals it's the world's most numerous penguin — yet most people have never heard of it." },
  { name: "Shovel-billed Kookaburra",
    fact: "Uses its flattened beak to dig through forest floor litter like a tiny bulldozer. Despite being related to the famous laughing kookaburra, it barely makes a sound." },
  { name: "Painted Bunting",
    fact: "The male is so colourful — blue head, red chest, green back — that it looks like it was painted by a child with every crayon. It's real, but illegal to keep as a pet in the US despite a huge black market." },
  { name: "Oilbird",
    fact: "The only nocturnal fruit-eating bird. Chicks get so fat on palm fruit they can weigh 50% more than their parents. Indigenous people harvested chicks and boiled them down for lamp oil — hence the name." },
  { name: "Lyrebird",
    fact: "Can mimic chainsaws, camera shutters, car alarms, and other birds with stunning accuracy. Its full display takes 20 minutes and involves mimicking up to 20 different species in sequence." },
  { name: "Harpy Eagle",
    fact: "Powerful enough to carry off monkeys and sloths. Its talons are the same size as a grizzly bear's claws. Despite being a massive apex predator, it nests in a single tree for years and raises only one chick at a time." },
  { name: "Vulturine Guineafowl",
    fact: "Despite the ominous name, it's a sociable bird that travels in gangs of up to 60. Recent research found they maintain complex social networks — groups that regularly interact but stay distinct, like human communities." },
  { name: "Snowy Sheathbill",
    fact: "The only land bird native to Antarctica with no webbed feet. Survives by scavenging — it steals fish from penguins mid-feed, eats penguin chicks, placentas, and anything else it can find. Basically Antarctica's rat." },
  { name: "Blue-footed Booby",
    fact: "Those blue feet aren't just for looking good — females literally judge a male's health by the brightness of his feet. They do a high-stepping dance to show them off. Young boobies have dull feet; old ones have spectacular ones." },
  { name: "Secretary Bird",
    fact: "A 1.3-metre tall eagle that walks. It hunts snakes by stamping them to death with scaly legs, delivering kicks with four times the force needed to break bone. Wears a punk feather crown." },
  { name: "Sword-billed Hummingbird",
    fact: "The only bird whose bill is longer than its body. It evolved specifically to reach nectar in a single species of passionflower — a perfect, exclusive co-dependency millions of years in the making." },
  { name: "Kea",
    fact: "The world's only alpine parrot. Keas are smart enough to solve multi-step puzzles and have been filmed dismantling car windscreen wipers for fun. In winter they sometimes ride avalanches down mountains." },
  { name: "Bearded Vulture",
    fact: "Deliberately dyes its white feathers orange-red by bathing in iron-rich mud — the only bird known to intentionally colour itself. Drops bones from heights of up to 80m to crack them open for marrow." },
  { name: "Resplendent Quetzal",
    fact: "Sacred to the ancient Maya and Aztec as a symbol of freedom — it was said to die in captivity. The male's iridescent tail streamers can exceed 60cm, nearly three times its body length." },
  { name: "Victoria Crowned Pigeon",
    fact: "The world's largest pigeon, roughly the size of a turkey. It wears an elaborate fan of blue-grey feathers tipped with white on its head, making it look perpetually overdressed for a formal occasion." },
  { name: "Wandering Albatross",
    fact: "Has the largest wingspan of any living bird — up to 3.5 metres. It can glide for hours without flapping a wing, circumnavigating the globe in a single trip, and lives for over 60 years." },
  { name: "Arctic Tern",
    fact: "Migrates from the Arctic to the Antarctic and back every year — a round trip of up to 90,000 km. Over a 30-year lifespan it travels the equivalent of three round trips to the Moon." },
  { name: "Peregrine Falcon",
    fact: "The fastest animal on Earth. In a hunting stoop it exceeds 390 km/h — fast enough that it needs special baffles in its nostrils to prevent its lungs from exploding from the air pressure." },
  { name: "Bar-headed Goose",
    fact: "Regularly crosses the Himalayas at altitudes above 8,000 metres, flying directly over Everest. Its blood carries oxygen more efficiently than almost any other vertebrate on the planet." },
  { name: "Hooded Pitohui",
    fact: "The first bird ever confirmed to be poisonous. Its skin and feathers contain batrachotoxin — the same nerve toxin found in poison dart frogs — absorbed from the Choresine beetles it eats." },
  { name: "Bowerbird",
    fact: "The male builds an elaborate avenue of sticks, then decorates it with hundreds of coloured objects — preferring blue. He arranges them by size to create forced perspective, making himself look bigger to watching females." },
  { name: "Western Parotia",
    fact: "Grows six wire-like head plumes tipped with reflective discs. During courtship it fluffs into a skirt shape and performs a precise ballerina-style dance, pivoting in tight circles for minutes at a time." },
  { name: "King-of-Saxony Bird-of-Paradise",
    fact: "The male grows two head plumes twice the length of its entire body, decorated with flags of enamel-blue along their length. No other structure like them exists in the animal kingdom." },
  { name: "Cassowary",
    fact: "Has a blade-like inner claw up to 12cm long used to disembowel threats with a single kick. It's considered the world's most dangerous bird — but is also a crucial rainforest gardener, dispersing the seeds of over 150 plants." },
  { name: "Emperor Penguin",
    fact: "Males fast for four months in Antarctic winter, standing in -60°C blizzards in rotating huddles to keep eggs warm. They lose half their body weight before the chick hatches and their partner returns." },
  { name: "Bee Hummingbird",
    fact: "The world's smallest bird — weighing just 1.6 grams and measuring 5cm, roughly the size of a bumblebee. Its wings beat 80 times per second, and its heart beats 1,200 times per minute." },
  { name: "Clark's Nutcracker",
    fact: "Hides up to 98,000 pine seeds across hundreds of locations each autumn and can remember where most of them are months later under metres of snow. This spatial memory is what allows whitebark pine forests to regenerate." },
  { name: "Burrowing Owl",
    fact: "One of the few birds that actively farms its food: it spreads dung around its burrow entrance to attract dung beetles, then eats the beetles. It also mimics a rattlesnake's rattle when disturbed inside its burrow." },
  { name: "Common Loon",
    fact: "Its haunting wail carries up to 10km across still water. Eyes turn blood-red in breeding season. It's so well adapted for diving that its bones are nearly solid — making it almost unable to walk on land." },
  { name: "Horned Screamer",
    fact: "Grows a thin 15cm horn of cartilage from its forehead. It also has sharp bony spurs on each wing used to fight rivals. Despite its fearsome appearance, it honks loudly and can be heard from several kilometres away." },
  { name: "Sunbittern",
    fact: "Appears to be a plain brown wading bird — until it spreads its wings to reveal a pair of large eye-like patterns that flash at predators. The display is so startling it has been known to send humans stumbling backwards." },
  { name: "Philippine Eagle",
    fact: "One of the largest and most powerful eagles on Earth. It hunts monkeys and flying lemurs through dense forest canopy with stunning agility. Critically endangered, with fewer than 800 individuals remaining." },
  { name: "Twelve-wired Bird-of-Paradise",
    fact: "The male's flank feathers end in 12 bare wire-like filaments. During courtship he presses these wires repeatedly against the female's face — for reasons scientists still don't fully understand." },
  { name: "Blue Bird-of-Paradise",
    fact: "Performs its display upside down, hanging from a branch and swaying while two iridescent blue tail wires curl outward. While displaying, it lowers its black breast shield to reveal a pulsing blue oval." },
  { name: "Tawny Frogmouth",
    fact: "Not an owl — it's related to nightjars. By day it freezes motionless on a branch, bill pointed upward, eyes slitted, looking exactly like a broken stub of wood. Hunters walk within arm's reach and never see it." },
  { name: "Roseate Spoonbill",
    fact: "Gets its shocking pink colour from the shrimp it eats — same as flamingos. It sweeps its spatula-shaped bill side to side through shallow water to feel for prey, rather than looking for it." },
  { name: "Osprey",
    fact: "The only hawk that plunge-dives feet-first into water to catch fish. Its outer toe is reversible so it can grip fish with two toes in front and two behind — like a fish-shaped clamp — and always rotates the catch to be aerodynamic." },
  { name: "Greater Roadrunner",
    fact: "Runs at 32 km/h and regularly kills rattlesnakes by grabbing the head and slamming it against a rock. It can also enter a controlled torpor on cold nights, rewarming itself in the morning by spreading its back feathers to expose dark skin to the sun." },
  { name: "Puffin",
    fact: "Can hold dozens of fish crosswise in its bill at once — the record is 83. Its tongue has backward-pointing spines that pin fish against the roof of its mouth, freeing it to open the bill and catch more without losing any." },
  { name: "Jabiru",
    fact: "The tallest flying bird in the Americas, standing 1.4 metres. In Brazilian Portuguese its name means 'swollen neck' — the male's bare neck pouch turns vivid red when it's aroused or agitated." },
  { name: "Great Grey Owl",
    fact: "Can hear a mouse moving under 60cm of packed snow from 100 metres away. It hunts entirely by sound, plunging face-first into deep snow and emerging with prey it never actually saw." },
  { name: "Bobolink",
    fact: "The only North American land bird that is black below and white above — the reverse of nearly every other bird. Migrates 20,000 km to Argentina each year, navigating partly by sensing Earth's magnetic field with crystals in its head." },
  { name: "Steller's Sea Eagle",
    fact: "The heaviest eagle on Earth at up to 9 kg, with a wingspan over 2.5 metres. Its orange bill is the largest of any eagle. It can carry off a full-grown salmon and is powerful enough to attack small deer." },
  { name: "Raggiana Bird-of-Paradise",
    fact: "The national bird of Papua New Guinea, whose plumes were once so sought-after for European hats that it was nearly hunted to extinction. Males gather in trees to display together, competing for females who silently inspect them." },
  { name: "Andean Condor",
    fact: "Has the largest wingspan of any land bird — up to 3.3 metres — and can soar for hours without a single wingbeat by riding thermal currents. It sometimes goes four or five days between meals, then eats up to 5 kg in one sitting." },
  { name: "Snowy Owl",
    fact: "Can pinpoint and catch a lemming moving under 30cm of snow using hearing alone. In boom years for lemmings, a single pair of snowy owls may raise 11 chicks; in lean years they may not breed at all." },
  { name: "Anna's Hummingbird",
    fact: "During its courtship dive, the male accelerates to 385 body-lengths per second — proportionally the fastest movement ever recorded for a vertebrate. At the bottom of the dive it emits a sharp chirp with its tail feathers." },
  { name: "Rifleman",
    fact: "New Zealand's smallest bird and one of its most ancient. The male is an iridescent green so bright it seems to glow; the female is streaky brown. They are the sole survivors of a bird family that split from all other birds over 80 million years ago." },
  { name: "Limpkin",
    fact: "Its screaming wail was used as the sound of the Hippogriff in the Harry Potter films and as various monster sounds in Hollywood. In reality it's a quiet wetland bird that specialises in eating apple snails, using its slightly twisted bill to extract them without breaking the shell." },
  { name: "Red Knot",
    fact: "Migrates from the Arctic to Tierra del Fuego — 15,000 km — twice a year. Each spring it stops on Delaware Bay to gorge on horseshoe crab eggs, nearly doubling its weight in two weeks before the final push to the breeding grounds." },
  { name: "Black Heron",
    fact: "Hunts by spreading its wings into a perfect black umbrella over the water. The canopy blocks glare, letting it see fish more clearly — and may also lure fish seeking shade. No other bird uses a tool made entirely from its own body." },
  { name: "Maleo",
    fact: "This Indonesian bird never incubates its own eggs. Instead it buries them in sun-warmed volcanic sand or geothermal ground, then abandons them. The chicks hatch fully feathered underground, dig out alone, and can fly within hours of birth." },
  { name: "Greater Honeyguide",
    fact: "The only bird known to actively lead humans to food. It uses a specific chattering call to recruit honey-hunters, guides them to a bees' nest, then waits for them to break it open before eating the wax and larvae left behind." },
  { name: "Andean Flamingo",
    fact: "One of the rarest flamingos in the world, with only around 33,000 remaining. It breeds on remote high-altitude salt lakes in the Andes at over 4,500 metres, where temperatures plunge below freezing every night." },
  { name: "Splendid Fairywren",
    fact: "The male is an improbably vivid cobalt blue. Despite being tiny, he maintains a 'harem' of several females and helpers. Females secretly mate with males from neighbouring territories — so most chicks are not raised by their biological father." },
  { name: "Frigatebird",
    fact: "Has the largest wingspan-to-bodyweight ratio of any bird, making it an effortless flier. It cannot land on water — its feathers are not waterproof — so it steals fish mid-air from other birds, a behaviour called kleptoparasitism." },
  { name: "Kiwi",
    fact: "The only bird with nostrils at the tip of its bill, used to sniff out earthworms underground. Its feathers are more like coarse hair than plumage. Its egg is so large — up to 20% of the female's body weight — that it's equivalent to a human giving birth to a six-year-old." },
  { name: "Turquoise-browed Motmot",
    fact: "The national bird of both El Salvador and Nicaragua. It has a distinctive racket-tipped tail it wags like a pendulum — possibly as a signal to predators that it has spotted them. The bare shaft of the tail feathers is created by the bird itself, preening the barbs off." },
  { name: "Long-tailed Widowbird",
    fact: "The male grows tail feathers up to 50cm long — four times its body length — purely for display. Females prefer males with the longest tails so strongly that scientists who tied on fake extensions found those males won dramatically more mates." },
];

// ── Hard-mode bird pool ───────────────────────────────────────────────────────
// All names follow "Color-bodypart Type" so they match the SNEAKY fake generator.
const HARD_BIRDS = [
  { name: "Yellow-rumped Warbler",
    fact: "The most numerous warbler in North America. Unlike most warblers it can digest waxy berries, letting it winter far north of other species. Its rump patch is so distinctive birders just call it 'butter butt.'" },
  { name: "Black-crowned Night Heron",
    fact: "Found on every continent except Australia and Antarctica — the world's most widespread heron. It hunts at dusk and night, and its stomach juices are so strong they dissolve fish bones entirely." },
  { name: "Red-tailed Hawk",
    fact: "The most common hawk in North America. Despite being everywhere, its screech is almost never heard in nature — Hollywood uses it as the sound effect for every eagle, osprey, and hawk on screen." },
  { name: "White-throated Sparrow",
    fact: "Comes in two colour forms — tan-striped and white-striped — that almost always mate with the opposite form. The two morphs differ in personality too: white-striped birds are more aggressive and promiscuous." },
  { name: "Blue-winged Teal",
    fact: "One of the earliest-leaving ducks each autumn — it departs for South America weeks before other species. It can detect the pressure drop before a storm and begins flying south immediately, travelling through the night." },
  { name: "Golden-fronted Woodpecker",
    fact: "Wedges acorns and grasshoppers into bark crevices to eat later — a behaviour so systematic that researchers have found caches of thousands of items in a single tree. Its golden forehead glows like a coin in sunlight." },
  { name: "Red-breasted Nuthatch",
    fact: "Paints sticky resin around the entrance of its nest hole — possibly to deter predators or parasites. It carries the resin in its bill, carefully avoiding the glue itself, and renews it throughout the breeding season." },
  { name: "Yellow-bellied Sapsucker",
    fact: "Drills neat rows of small holes to let sap ooze out, then laps it up along with trapped insects. At least 35 other species — including hummingbirds — rely on sapsucker wells as a food source." },
  { name: "Golden-crowned Kinglet",
    fact: "One of North America's smallest birds at just 6 grams. It survives winters at -40°C by huddling in groups and shivering continuously through the night to maintain body temperature." },
  { name: "Black-bellied Plover",
    fact: "Has a hidden fourth toe that other plovers lack. Its plumage transforms completely between seasons — jet-black below in summer, pale grey in winter — making it look like two different species." },
  { name: "White-crowned Sparrow",
    fact: "Has distinct regional dialects: a bird from San Francisco sings a song its cousins in Alaska would not recognise. Young males learn the local dialect within weeks of hatching and sing it for life." },
  { name: "Chestnut-backed Chickadee",
    fact: "Hides thousands of individual seeds in separate locations each autumn and can find most of them months later under deep snow. Its hippocampus — the brain's memory centre — grows measurably larger each autumn." },
  { name: "Rufous-tailed Hummingbird",
    fact: "The commonest hummingbird in Central America, yet it visits over 150 plant species and acts as the primary pollinator for dozens of them. Males defend flowering trees so fiercely they will chase away birds ten times their size." },
  { name: "Black-backed Woodpecker",
    fact: "Specialises in freshly burned forests, arriving within months of a fire. It can apparently detect smoke from dozens of kilometres away. Its sooty-black back camouflages it perfectly against charred tree trunks." },
  { name: "Olive-backed Sunbird",
    fact: "Weighs just 6 grams and hovers like a hummingbird, but actually prefers to perch while feeding. The male's throat is a blaze of metallic purple and yellow, visible only in direct sunlight." },
  { name: "White-bellied Sea Eagle",
    fact: "Hunts fish, sea snakes, and waterbirds by swooping low over the water and snatching prey in its talons without getting wet. Pairs mate for life and reuse the same nest for decades, adding new sticks each year until it can weigh a tonne." },
  { name: "Rufous-crowned Sparrow",
    fact: "A desert specialist of rocky hillsides in the American Southwest. It rarely drinks free water, extracting all the moisture it needs from insects and seeds. It walks rather than hops, creeping mouse-like between boulders." },
  { name: "Yellow-billed Oxpecker",
    fact: "Rides large African mammals eating ticks, but also keeps wounds open to drink blood — making it partly parasitic on the very animals it appears to help. Buffalo tolerate it; elephants and rhinos often do not." },
  { name: "Blue-naped Mousebird",
    fact: "Hangs upside-down like a bat to roost, packing into tight clusters of up to 20 birds. In cold mornings it basks with wings spread and belly facing the sun, raising its temperature before it can fly." },
  { name: "Chestnut-sided Warbler",
    fact: "One of the few bird species to have genuinely benefited from deforestation — it barely existed in Audubon's time but thrived as settlers cleared eastern forests. Males sing two distinct song types: one to attract females, one to warn rivals." },
  { name: "Red-faced Cormorant",
    fact: "Found only in the Aleutian Islands and Kamchatka, one of the rarest cormorants in the world. The red face skin becomes brilliantly coloured in breeding season, fading to dull brown for the rest of the year." },
  { name: "White-winged Crossbill",
    fact: "Its crossed bill is purpose-built for prying open spruce cones — it inserts the bill, twists, and flicks out the seed in one motion. It wanders nomadically across northern forests following cone crops." },
  { name: "Black-headed Grosbeak",
    fact: "One of the few birds that can eat monarch butterflies despite their milkweed toxins. It appears to tolerate the poison by feeding in short bursts, alternating with other food to avoid build-up." },
  { name: "Yellow-fronted Canary",
    fact: "Native to sub-Saharan Africa but established as a feral population in Hawaii after cage-bird escapes. Males can mimic the songs of other species mid-song, seamlessly stitching foreign phrases into their own." },
  { name: "Rufous-bellied Niltava",
    fact: "A Himalayan forest bird whose male is an electric combination of deep blue above and fiery rufous below. Its colours are so intense it was once called one of the most beautiful birds in Asia by early naturalists." },
];
